### PR TITLE
TypeError: Cannot read property '1' of null

### PR DESCRIPTION
**Pull request by myfreax**
-  fix match return null in chrome 
```
TypeError: Cannot read property '1' of null
```
- added should return an empty array in test

### CODE REVIEW

**Comment by Wildhoney** [comment]
The perfect PR with tests! Thanks @huangyanxiong01 👍 Releasing now.

**Comment by myfreax** [comment]
@Wildhoney I found a problem, getPropertyValue function can not work and it return empty in the chrome, how to solve it

**Comment by Wildhoney** [comment]
I noticed that myself yesterday and updated the [function chain](https://github.com/Wildhoney/DetectFont/blob/master/src/detect-font.js#L94) to check for `style` as well &ndash; all tests seem to now pass in Chrome, however if you're still having issues with Chrome, please write-up a failing test for your case and I'll see what I can do.

**Comment by myfreax** [comment]
:tada: After the update can work very well

**Pull request merged**
